spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:social-multiplication

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true